[versions]
# The latest versions are available at https://lambdaurora.dev/tools/import_quilt.html
minecraft = "1.19.2"
quilt_mappings = "1.19.2+build.14"
quilt_loader = "0.17.5-beta.1"

quilted_fabric_api = "4.0.0-beta.10+0.60.0-1.19.2"
cca = "5.0.2"
patchouli = "1.19.2-76-FABRIC"
midnightlib = "0.6.0"
blabber = "0.4.0"
mixinextras = "0.0.12"
lucko_perms = "0.1-SNAPSHOT"
modmenu = "4.0.6"

[libraries]
minecraft = { module = "com.mojang:minecraft", version.ref = "minecraft" }
quilt_mappings = { module = "org.quiltmc:quilt-mappings", version.ref = "quilt_mappings" }
quilt_loader = { module = "org.quiltmc:quilt-loader", version.ref = "quilt_loader" }

quilted_fabric_api = { module = "org.quiltmc.quilted-fabric-api:quilted-fabric-api", version.ref = "quilted_fabric_api" }
quilted_fabric_api_deprecated = { module = "org.quiltmc.quilted-fabric-api:quilted-fabric-api-deprecated", version.ref = "quilted_fabric_api" }
cca_base = { module = "dev.onyxstudios.cardinal-components-api:cardinal-components-base", version.ref = "cca" }
cca_entity = { module = "dev.onyxstudios.cardinal-components-api:cardinal-components-entity", version.ref = "cca" }
patchouli = { module = "vazkii.patchouli:Patchouli", version.ref = "patchouli" }
midnightlib = { module = "maven.modrinth:midnightlib", version.ref = "midnightlib" }
blabber = { module = "io.github.ladysnake:blabber", version.ref = "blabber" }
mixinextras = { module = "com.github.LlamaLad7:MixinExtras", version.ref = "mixinextras" }
lucko_perms = { module = "me.lucko:fabric-permissions-api", version.ref = "lucko_perms" }
modmenu = { module = "com.terraformersmc:modmenu", version.ref = "modmenu" }

# If you have multiple similar dependencies, you can declare a dependency bundle and reference it on the build script with "libs.bundles.example".
[bundles]
quilted_fabric_api = ["quilted_fabric_api", "quilted_fabric_api_deprecated"]

[plugins]
quilt_loom = { id = "org.quiltmc.loom", version = "0.12.+" }
